---
#- name: Baisc repos update, packages update and installation
#  hosts: all
#  gather_facts: true
#  roles:
#    - base

- name: virtualization host
  hosts: 192.168.1.170
  gather_facts: true
  tags: virt_host
  roles:
    - base
    - desktop_config
    - virtualization
    - docker

- name: configure pihole
  hosts: 192.168.1.150
  gather_facts: true
  tags: pihole
  roles:
    - base
    - pihole

- name: configure backup host
  hosts: 192.168.1.179
  gather_facts: true
  tags: backup
  roles:
    - base
    - backup
