- name: copy config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: enrico
    group: enrico
    force: yes
    mode: u=rw,g=r,o=r
  loop:
      # Lazy Librarian
    - { src: 'qBittorrent-data.conf', dest: '/home/enrico/.config/qBittorrent/qBittorrent-data.conf' }
    - { src: 'qBittorrent.conf', dest: '/home/enrico/.config/qBittorrent/qBittorrent.conf' }
      # qBittorrent
    - { src: 'config.ini', dest: '/opt/lazy_librarian/config.ini' }
      # Calibre
    - { src: 'gui.json', dest: '/home/enrico/.config/calibre/gui.json' }
    - { src: 'gui.py.json', dest: '/home/enrico/.config/calibre/gui.py.json' }
