- name: install packages
  package:
    name:    
      - git
      - python3-pip
      - python3-pip
      - python3-openssl
      - python3-oauth
      - libnss3
      - vim
      - qbittorrent-nox
      - openjdk-8-jre #booksonic
      - ffmpeg #booksonic
    state: latest

### BOOKSONIC ###
- name: BOOKSONIC Create Booksonic dir
  ansible.builtin.file:
    path: /opt/booksonic
    state: directory
    mode: '0755'
    owner: enrico
    group: enrico

- name: BOOKSONIC download Booksonic 
  get_url:
    url: https://github.com/popeen/Booksonic-Air/releases/download/v2009.1.0/booksonic.war
    dest: /opt/booksonic/booksonic.war
    mode: '0744'

- name: BOOKSONIC Change permission
  ansible.builtin.file:
    path: /opt/booksonic/booksonic.war
    state: file
    mode: '0755'
    owner: enrico
    group: enrico

### CALIBRE-WEB ###
- name: CALIBRE-WEB download calibre-web script 
  get_url:
    url: https://github.com/janeczku/calibre-web/archive/master.zip
    dest: /home/enrico/Downloads/master.zip
    mode: '0744'

# Unzip the master.zip and move the content in /opt/calibre-web

- name: CALIBRE-WEB Install dependecies python packages
  pip:
    requirements: /opt/calibre-web/requirements.txt

### CALIBRE ###
- name: CALIBRE Create directory
  ansible.builtin.file:
    path: /home/enrico/logs
    state: directory
    mode: '0755'
    owner: enrico
    group: enrico

- name: CALIBRE Create logs
  ansible.builtin.file:
    path: /home/enrico/logs/calibre.log
    state: touch
    mode: '0644'
    owner: enrico
    group: enrico

- name: CALIBRE download calibre script 
  get_url:
    url: https://download.calibre-ebook.com/linux-installer.sh
    dest: /home/enrico/Downloads/calibre-installer.sh
    mode: '0744'

# - name: CALIBRE run calibre installer
#   ansible.builtin.script: /home/enrico/Downloads/calibre-installer.sh

# - name: CALIBRE remove calibre installer
#   ansible.builtin.file:
#     path: /home/enrico/Downloads/calibre-installer.sh
#     state: absent

# TO CREATE USER
# sudo calibre-server --userdb /home/enrico/.config/calibre/server-users.sqlite --manage-users    

### LAZY LIBRARIAN ###
- name: LAZY LIBRARIAN Create Lazy Librarian dir
  ansible.builtin.file:
    path: /opt/lazy_librarian
    state: directory
    mode: '0755'
    owner: enrico
    group: enrico

- name: LAZY LIBRARIAN Git checkout
  ansible.builtin.git:
    repo: 'https://gitlab.com/LazyLibrarian/LazyLibrarian.git'
    dest: /opt/lazy_librarian

- name: LAZY LIBRARIAN Chown Lazy Librarian
  ansible.builtin.file:
    path: /opt/lazy_librarian
    owner: enrico
    group: enrico
    recurse: yes