
- name: update repository index (Rocky)
  yum:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Rocky"

- name: Upgrade all packages (Rocky)
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Rocky"

- name: install epel release
  dnf:
    name: epel-release
  when: ansible_distribution == "Rocky"


- name: update repository index (ubuntu)
  apt:
    update_cache: yes
    upgrade: dist
  changed_when: false
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Pop!_OS"

- name: install basic packages
  package:
    name:
      - vim
      - bash-completion
      - python3
      - python3-pip
      - htop
      - rsync
      - git
    state: latest