- name: add seafile apt key
  apt_key:
    url: "https://linux-clients.seafile.com/seafile.asc"
    keyring: /usr/share/keyrings/seafile-keyring.asc
    state: present
- name: add seafile repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/seafile-keyring.asc]  https://linux-clients.seafile.com/seafile-deb/{{ ansible_distribution_release }}/ stable main"
    state: present
    filename: seafile

- name: Add an Brave signing key
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    state: present
- name: Add brave repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: brave

- name: add docker key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: docker

- name: add spotify repo key
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_0D811D58.gpg"
    keyring: /usr/share/keyrings/spotify-archive-keyring.gpg
    state: present
- name: add spotify repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/spotify-archive-keyring.gpg] http://repository.spotify.com stable non-free"
    state: present
    filename: spotify

- name: add microsoft key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present
- name: Azure-cli repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release | lower }} main"
    state: present
    filename: azurecli
- name: add Visual Studio Code repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode

- name: apt update and upgrade 
  apt: 
    update_cache: yes
#    upgrade: full