- name: create backup directories
  file:
    path: "{{ item }}"
    state: directory
    owner: enrico
    group: enrico
  loop:
    - /volumes/backup/desk.enricoruggieri.com
    - /volumes/backup/minecraft.enricoruggieri.com
    - /volumes/backup/kvm
    - /volumes/backup/home.desk
    - /volumes/backup/photos
      
- name: copy backup exclude files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/enrico/.local/bin/
    group: root
    owner: root
    force: yes
  loop:
    - backup_scripts/exclude.home.desk
    - backup_scripts/exclude.home.tv
    - backup_scripts/exclude.media

- name: copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/enrico/.local/bin/
    owner: root
    group: root
    mode: 0744
    force: yes
  loop:
    - backup_scripts/rdiff-backup.sh
    - start_vm.sh
    - "off"
    - reb

